### ISSUE TITLE
LICENSEファイルの追加をお願いします

### ISSUE THREAD

**Issue by hnakamur** [ariarijp/elasticsearch-and-kibana-playbook#1]
まずはじめに、便利なPlaybookをありがとうございます！

本題ですが、是非LICENSEファイルの追加をお願いします。

ライセンスを選ぶのには下記のページが参考になるかもしれません。
[Githubによる、オープンソースライセンスの選び方 | オープンソース・ライセンスの談話室](http://www.catch.jp/oss-license/2013/09/10/github/)

**Comment by ariarijp** [comment]
ご指摘ありがとうございました。

LICENSEファイルを追加し、READMEもあわせて更新しました。

**Comment by hnakamur** [comment]
ご対応ありがとうございました！
